with bike_data  as (
select 
    TRIP_DURATION as TRIPDURATION,
    START_TIME as STARTTIME,
    STOP_TIME as STOPTIME,
    START_STATION_ID,
    START_STATION_NAME,
    START_STATION_LATITUDE,
    START_STATION_LONGITUDE,
    END_STATION_ID,
    END_STATION_NAME,
    END_STATION_LATITUDE,
    END_STATION_LONGITUDE,
    BIKE_ID as BIKEID,
    USER_TYPE as USERTYPE,
    BIRTH_YEAR,
    GENDER  
 from {{ source('demo', 'BIKE_DATA_AFTER_STAGGING_2016') }}) 
select * from bike_data